name: Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mayapp'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONT }}
          package: '.'
